services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: "sqlite+aiosqlite:///./test.db"
    env_file:
      - .env
    # depends_on:
    #   - db
  # db:
  #   image: postgres:alpine
  #   ports:
  #     - "5432:5432"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data:cached