services:
  app:
    container_name: fastapi
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80"
    build: .
    restart: on-failure
    ports:
      - "8000:80"
    volumes:
      - .:/code/
    env_file:
      - .env.example
    depends_on:
      db:
        condition:
          service_healthy

  db:
    container_name: postgres
    image: postgres:15-bullseye
    ports:
      - "5432:5432"
    env_file:
      - .env.example
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -t 5 -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data:cached

volumes:
  postgres_data:
    name: ecommerce_data
