"""all_models

Revision ID: 36994ca6d50b
Revises:
Create Date: 2023-04-11 10:23:03.883950

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '36994ca6d50b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('guid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_guid'), 'users', ['guid'], unique=False)
    op.create_table('products',
    sa.Column('guid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('producer', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_products_guid'), 'products', ['guid'], unique=False)
    op.create_table('ratings',
    sa.Column('guid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('product_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.guid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_ratings_guid'), 'ratings', ['guid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_guid'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_products_guid'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_guid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
