"""rating_model

Revision ID: 8f715c6937ef
Revises: 0c56da63097e
Create Date: 2023-04-07 10:06:34.088555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f715c6937ef'
down_revision = '0c56da63097e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
