"""fix_name_in rating

Revision ID: d3348183face
Revises: ff3e192722c3
Create Date: 2023-04-10 22:01:46.396627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3348183face'
down_revision = 'ff3e192722c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('stars', sa.Integer(), nullable=True))
    op.drop_column('ratings', 'starts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('starts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('ratings', 'stars')
    # ### end Alembic commands ###
